# Generated by Django 3.0.6 on 2020-05-14 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
